### ISSUE TITLE
build error while using jsonwebtokens in Angular6

### ISSUE THREAD

**Issue by thatham** [brianloveswords/node-jwa#28]
ERROR in ./node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in 'E:\My Code\mycode\pwa\node_modules\jwa'

**Comment by omsmith** [comment]
You've already reported this, and the answer is still the same. _crypto_, _stream_ etc are all core node modules. In a browser environment they're generally poly-filled by by your bundler.

Try a fresh `npm install`, but otherwise you'll have to raise the issue with Angular or WebPack or whoever.

Ref: https://github.com/brianloveswords/node-jwa/issues/25
